version: '3'
services:
  nginx:
    build: images/nginx
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    links:
      - php
  php:
    build: images/php
    volumes:
      - ./:/var/www
    command: bash /var/www/post.sh
    ports:
      - "9000:9000"
